version: '2'
services:
  node_prueba:
    image: node
    container_name: node_test
    ports:
      - 4000:4000
    build: .
    command: 'node index'
  db:
    image: mongo
    container_name: mymongoo
    ports:
      - 27017:27017

